title: Hello, world! I'm Viet NT
description: > # this means to ignore newlines until "baseurl:" Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  Ký sự IT, ký sự làm lập trình, kiến thức về lập trình, kiến thức về IT, học IT như nào, chia sẻ kiến thức IT
categories: Uncategorized
permalink: '/:categories/:title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kysuit.net" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here
site-name: "KysuIT.net"

# Author Settings
author: Viet Nguyen Tien # add your name
author-img: vietnt-avatar.png # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: httv_hut
social-facebook: RubyPhantom
social-github: toilamit
social-linkedin: vietnt
social-email: toilamit.com@gmail.com

# Disqus
discus-identifier: toilamit # add your discus identifier

# Fb-comment
enable-fb-comment: true

# Tracker
analytics: UA-48430890-7 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
